name: TTO
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - ampl-asl=1.0.0
  - asttokens=3.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - cairo=1.18.4
  - clarabel=0.11.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.2
  - cpython=3.10.18
  - cvxpy=1.6.6
  - cvxpy-base=1.6.6
  - cycler=0.12.1
  - cyipopt=1.5.0
  - debugpy=1.8.14
  - decorator=5.2.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.4
  - freetype=2.13.3
  - graphite2=1.3.14
  - harfbuzz=11.2.1
  - icu=75.1
  - importlib-metadata=8.7.0
  - intel-openmp=2024.2.1
  - ipopt=3.14.17
  - ipykernel=6.29.5
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=20.1.7
  - libdeflate=1.24
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libosqp=0.6.3
  - libpng=1.6.49
  - libqdldl=0.1.7
  - libsodium=1.0.20
  - libsqlite=3.50.2
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=20.1.7
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mkl=2024.2.2
  - mumps-seq=5.7.3
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openssl=3.5.1
  - osqp=0.6.7.post3
  - packaging=25.0
  - parso=0.8.4
  - pcre2=10.45
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.1.1
  - pixman=0.46.2
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pywin32=307
  - pyzmq=27.0.0
  - qdldl-python=0.1.7.post5
  - qhull=2020.2
  - qt6-main=6.9.1
  - scipy=1.15.2
  - scs=3.2.7.post2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tbb=2021.13.0
  - tk=8.6.13
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstd=1.5.7